#!/bin/bash

# Claude Providers Installer
# https://github.com/hubertkirch/claude-providers
#
# Install: curl -sSL https://raw.githubusercontent.com/hubertkirch/claude-providers/main/install.sh | bash
# Or:      bash install.sh
#
# This script sets up Claude Code to work with different LLM providers:
# - GLM (z.ai)
# - MiniMax
# - OpenRouter

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Version
VERSION="1.0.0"

# Configuration
CONFIG_DIR="$HOME/.claude-configs"

# Print colored output
print_color() {
    local color=$1
    shift
    echo -e "${color}$*${NC}"
}

# Header
print_header() {
    echo ""
    print_color "$BLUE" "╔════════════════════════════════════════╗"
    print_color "$BLUE" "║     Claude Providers Installer        ║"
    print_color "$BLUE" "║           Version $VERSION                ║"
    print_color "$BLUE" "╚════════════════════════════════════════╝"
    echo ""
}

# Detect Claude Code installation
detect_claude() {
    local claude_bin=$(which claude 2>/dev/null)

    if [ -z "$claude_bin" ]; then
        print_color "$RED" "❌ Error: Claude Code not found" >&2
        echo "Please install Claude Code first: https://claude.ai/download" >&2
        exit 1
    fi

    print_color "$GREEN" "✓ Found Claude Code at: $claude_bin" >&2
    echo "$claude_bin"  # Only output the path itself
}

# Detect best installation directory
detect_install_dir() {
    local install_dir=""

    # Check if ~/.local/bin is in PATH
    if [[ ":$PATH:" == *":$HOME/.local/bin:"* ]]; then
        install_dir="$HOME/.local/bin"
        print_color "$GREEN" "✓ Using ~/.local/bin (already in PATH)" >&2
    # Check if /usr/local/bin is writable
    elif [[ -w "/usr/local/bin" ]]; then
        install_dir="/usr/local/bin"
        print_color "$GREEN" "✓ Using /usr/local/bin" >&2
    else
        install_dir="$HOME/.local/bin"
        print_color "$YELLOW" "⚠ Using ~/.local/bin (not in PATH)" >&2
        echo "" >&2
        print_color "$YELLOW" "Add to your PATH by adding this to ~/.bashrc or ~/.zshrc:" >&2
        echo '    export PATH="$HOME/.local/bin:$PATH"' >&2
        echo "" >&2
        read -p "Continue anyway? (y/n): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi

    # Create directory if it doesn't exist
    mkdir -p "$install_dir"
    echo "$install_dir"  # Only output the path itself
}

# Provider configurations using functions for compatibility
get_provider_name() {
    case "$1" in
        glm) echo "GLM (z.ai)" ;;
        minimax) echo "MiniMax" ;;
        openrouter) echo "OpenRouter" ;;
    esac
}

get_provider_url() {
    case "$1" in
        glm) echo "https://api.z.ai/api/anthropic" ;;
        minimax) echo "https://api.minimax.io/anthropic" ;;
        openrouter) echo "https://openrouter.ai/api" ;;
    esac
}

get_provider_model() {
    case "$1" in
        glm) echo "glm-4.7" ;;
        minimax) echo "MiniMax-M2.1" ;;
        openrouter) echo "" ;;  # OpenRouter doesn't use default models
    esac
}

get_provider_timeout() {
    case "$1" in
        glm) echo "3000000" ;;
        minimax) echo "120000" ;;
        openrouter) echo "120000" ;;
    esac
}

get_provider_description() {
    case "$1" in
        glm) echo "GLM-4 from z.ai - Fast and efficient" ;;
        minimax) echo "MiniMax AI - Good for specialized tasks" ;;
        openrouter) echo "Access multiple models through one API" ;;
    esac
}

# Install a provider
install_provider() {
    local provider=$1
    local claude_bin=$2
    local install_dir=$3
    local api_key=""

    print_color "$BLUE" "\n📦 Installing $(get_provider_name "$provider")..."
    echo "$(get_provider_description "$provider")"

    # Get API key
    echo ""
    read -s -p "Enter your $(get_provider_name "$provider") API key: " api_key
    echo ""  # New line after password entry

    if [ -z "$api_key" ]; then
        print_color "$RED" "❌ API key cannot be empty"
        return 1
    fi

    # Confirm API key was entered
    print_color "$GREEN" "✓ API key received (${#api_key} characters)"
    echo ""
    read -p "Press Enter to continue with installation... "
    echo ""

    # Create standard version
    local script_path="$install_dir/claude-$provider"

    cat > "$script_path" <<EOF
#!/bin/bash
# Claude instance: $provider
# Generated by claude-providers installer v$VERSION
# Date: $(date)

CLAUDE_BIN="$claude_bin"

export CLAUDE_HOME="\$HOME/.claude-$provider"
export ANTHROPIC_AUTH_TOKEN="$api_key"
export ANTHROPIC_BASE_URL="$(get_provider_url "$provider")"
export API_TIMEOUT_MS="$(get_provider_timeout "$provider")"
EOF

    # Add model mappings for non-OpenRouter providers
    if [ "$provider" != "openrouter" ]; then
        cat >> "$script_path" <<EOF
export ANTHROPIC_DEFAULT_OPUS_MODEL="$(get_provider_model "$provider")"
export ANTHROPIC_DEFAULT_SONNET_MODEL="$(get_provider_model "$provider")"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="$(get_provider_model "$provider")"
EOF
    else
        # OpenRouter needs empty API key and model check
        cat >> "$script_path" <<EOF
export ANTHROPIC_API_KEY=""  # Must be empty for OpenRouter

# OpenRouter requires explicit model selection
if [[ ! " \$* " =~ " --model " ]]; then
    echo "Error: OpenRouter requires --model parameter"
    echo ""
    echo "Usage: claude-openrouter --model 'model-name' [other args]"
    echo ""
    echo "Popular models:"
    echo "  anthropic/claude-3.5-sonnet"
    echo "  openai/gpt-4-turbo"
    echo "  google/gemini-pro"
    echo "  meta-llama/llama-3.1-70b"
    echo ""
    echo "See https://openrouter.ai/models for full list"
    exit 1
fi
EOF
    fi

    # Complete the standard script
    cat >> "$script_path" <<EOF

exec "\$CLAUDE_BIN" "\$@"
EOF

    chmod 700 "$script_path"
    print_color "$GREEN" "✓ Created: claude-$provider"

    # Create auto version
    local auto_script_path="$install_dir/claude-$provider-auto"

    cat > "$auto_script_path" <<EOF
#!/bin/bash
# Claude instance: $provider (auto-approval)
# Generated by claude-providers installer v$VERSION
# Date: $(date)

CLAUDE_BIN="$claude_bin"

export CLAUDE_HOME="\$HOME/.claude-$provider"
export ANTHROPIC_AUTH_TOKEN="$api_key"
export ANTHROPIC_BASE_URL="$(get_provider_url "$provider")"
export API_TIMEOUT_MS="$(get_provider_timeout "$provider")"
EOF

    # Add model mappings for non-OpenRouter providers
    if [ "$provider" != "openrouter" ]; then
        cat >> "$auto_script_path" <<EOF
export ANTHROPIC_DEFAULT_OPUS_MODEL="$(get_provider_model "$provider")"
export ANTHROPIC_DEFAULT_SONNET_MODEL="$(get_provider_model "$provider")"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="$(get_provider_model "$provider")"
EOF
    else
        cat >> "$auto_script_path" <<EOF
export ANTHROPIC_API_KEY=""  # Must be empty for OpenRouter

# OpenRouter requires explicit model selection
if [[ ! " \$* " =~ " --model " ]]; then
    echo "Error: OpenRouter requires --model parameter (even in auto mode)"
    echo "Usage: claude-openrouter-auto --model 'model-name' [other args]"
    exit 1
fi
EOF
    fi

    # Complete the auto script
    cat >> "$auto_script_path" <<EOF

exec "\$CLAUDE_BIN" --dangerously-skip-permissions "\$@"
EOF

    chmod 700 "$auto_script_path"
    print_color "$GREEN" "✓ Created: claude-$provider-auto"

    # Save configuration (for tracking only, no API keys)
    mkdir -p "$CONFIG_DIR"
    cat > "$CONFIG_DIR/$provider.json" <<EOF
{
  "provider": "$provider",
  "installed": true,
  "version": "$VERSION",
  "created": "$(date -Iseconds)",
  "install_dir": "$install_dir",
  "script_path": "$script_path",
  "auto_script_path": "$auto_script_path"
}
EOF

    print_color "$GREEN" "✓ Installation complete!"

    # Show usage
    echo ""
    print_color "$BLUE" "Usage:"
    if [ "$provider" == "openrouter" ]; then
        echo "  claude-$provider --model 'anthropic/claude-3.5-sonnet' \"Your prompt\""
        echo "  claude-$provider-auto --model 'openai/gpt-4-turbo' -p \"Your prompt\""
    else
        echo "  claude-$provider \"Your prompt\""
        echo "  claude-$provider-auto -p \"Your prompt\""
    fi
}

# List installed providers
list_providers() {
    print_color "$BLUE" "\n📋 Installed providers:"
    echo ""

    if [ ! -d "$CONFIG_DIR" ]; then
        echo "No providers installed yet."
        return
    fi

    local found=false
    for config in "$CONFIG_DIR"/*.json; do
        if [ -f "$config" ]; then
            found=true
            local provider=$(basename "$config" .json)
            local script_path=$(grep -o '"script_path": "[^"]*' "$config" | cut -d'"' -f4)

            if [ -f "$script_path" ]; then
                print_color "$GREEN" "• claude-$provider"
                echo "  Location: $script_path"
                echo "  Auto version: ${script_path}-auto"
                echo ""
            fi
        fi
    done

    if [ "$found" = false ]; then
        echo "No providers installed yet."
    fi
}

# Remove a provider
remove_provider() {
    local provider=$1

    if [ ! -f "$CONFIG_DIR/$provider.json" ]; then
        print_color "$RED" "Provider '$provider' not installed"
        return 1
    fi

    local install_dir=$(grep -o '"install_dir": "[^"]*' "$CONFIG_DIR/$provider.json" | cut -d'"' -f4)

    print_color "$YELLOW" "Removing claude-$provider..."

    rm -f "$install_dir/claude-$provider"
    rm -f "$install_dir/claude-$provider-auto"
    rm -f "$CONFIG_DIR/$provider.json"

    print_color "$GREEN" "✓ Removed claude-$provider"
}

# Interactive menu
interactive_menu() {
    local claude_bin=$1
    local install_dir=$2

    while true; do
        echo ""
        print_color "$BLUE" "Select provider to install:"
        echo "1) GLM (z.ai)"
        echo "2) MiniMax"
        echo "3) OpenRouter"
        echo "4) Install ALL"
        echo "5) List installed"
        echo "6) Remove provider"
        echo "7) Exit"
        echo ""
        read -p "Choice (1-7): " choice

        case $choice in
            1) install_provider "glm" "$claude_bin" "$install_dir" ;;
            2) install_provider "minimax" "$claude_bin" "$install_dir" ;;
            3) install_provider "openrouter" "$claude_bin" "$install_dir" ;;
            4)
                install_provider "glm" "$claude_bin" "$install_dir"
                install_provider "minimax" "$claude_bin" "$install_dir"
                install_provider "openrouter" "$claude_bin" "$install_dir"
                ;;
            5) list_providers ;;
            6)
                read -p "Provider to remove (glm/minimax/openrouter): " provider
                remove_provider "$provider"
                ;;
            7)
                print_color "$GREEN" "Goodbye!"
                exit 0
                ;;
            *)
                print_color "$RED" "Invalid choice"
                ;;
        esac
    done
}

# Main execution
main() {
    print_header

    # Detect Claude Code
    local claude_bin=$(detect_claude)

    # Detect installation directory
    local install_dir=$(detect_install_dir)

    # Check command line arguments
    case "${1:-}" in
        glm|minimax|openrouter)
            # Quick install single provider
            if [ -n "${2:-}" ]; then
                # API key provided
                install_provider "$1" "$claude_bin" "$install_dir" <<< "$2"
            else
                install_provider "$1" "$claude_bin" "$install_dir"
            fi
            ;;
        all)
            # Install all providers
            install_provider "glm" "$claude_bin" "$install_dir"
            install_provider "minimax" "$claude_bin" "$install_dir"
            install_provider "openrouter" "$claude_bin" "$install_dir"
            ;;
        list)
            list_providers
            ;;
        remove)
            if [ -n "${2:-}" ]; then
                remove_provider "$2"
            else
                print_color "$RED" "Usage: $0 remove <provider>"
            fi
            ;;
        help|--help|-h)
            echo "Usage: $0 [command] [options]"
            echo ""
            echo "Commands:"
            echo "  glm [API_KEY]       Install GLM provider"
            echo "  minimax [API_KEY]   Install MiniMax provider"
            echo "  openrouter [KEY]    Install OpenRouter provider"
            echo "  all                 Install all providers"
            echo "  list                List installed providers"
            echo "  remove <provider>   Remove a provider"
            echo "  help                Show this help"
            echo ""
            echo "Interactive mode:"
            echo "  $0                  Start interactive installation"
            ;;
        "")
            # Interactive mode
            interactive_menu "$claude_bin" "$install_dir"
            ;;
        *)
            print_color "$RED" "Unknown command: $1"
            echo "Run '$0 help' for usage"
            exit 1
            ;;
    esac
}

# Run main
main "$@"